[package]
name = "rfe"
version = "0.1.0"
authors = ["Zach Leytus <zach.leytus@pm.me>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
num_enum = "0.5.1"
serialport = "3.3.0"
thiserror = "1.0.20"
