[package]
name = "rfe"
version = "0.1.0"
authors = ["Zach Leytus <zach.leytus@pm.me>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
chrono = "0.4"
num_enum = "0.5.1"
rfe_message = { path = "rfe_message" }
serialport = "3.3.0"
thiserror = "1.0.20"
