[package]
name = "rfe_message"
version = "0.1.0"
authors = ["Zach Leytus <zach.leytus@pm.me>"]
edition = "2018"

[dependencies]
quote = "1.0"
thiserror = "1.0"

[dependencies.syn]
version = "1.0"
default-features = true
features = ["extra-traits"]

[lib]
proc-macro = true
